# Generated by Django 4.1 on 2023-01-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='max_queues',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
