# Generated by Django 4.1 on 2023-01-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_party_max_queues'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_host', models.BooleanField(default=False)),
                ('room_code', models.CharField(max_length=4)),
            ],
        ),
        migrations.RenameField(
            model_name='party',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
