# Generated by Django 4.1 on 2023-01-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='party',
        ),
    ]
