# Generated by Django 4.1 on 2023-01-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='party_code',
            field=models.CharField(default='aaaa', max_length=4),
            preserve_default=False,
        ),
    ]
