# Generated by Django 4.1 on 2023-01-04 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
