# Generated by Django 4.1 on 2023-01-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_playback_song_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='image_url',
            new_name='album_cover',
        ),
        migrations.AlterField(
            model_name='song',
            name='time',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
