# Generated by Django 4.1 on 2023-01-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_image_url_song_album_cover_alter_song_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_cover',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
