# Generated by Django 4.1 on 2023-01-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_song_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='time',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
