# Generated by Django 4.1 on 2023-01-04 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_song_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='playback',
            name='username',
            field = models.CharField(default='aaaa', max_length=20),
            preserve_default=False,
        ),
    ]