# Generated by Django 4.1 on 2023-01-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_song_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_cover',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
