# Generated by Django 4.1 on 2023-01-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_song_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
