# Generated by Django 4.1 on 2023-01-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_queue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='party_code',
            field=models.CharField(default='aaaa', max_length=4),
            preserve_default=False,
        ),
    ]
