# Generated by Django 4.1 on 2023-01-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_queue_party_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='fire',
            field=models.IntegerField(default=0),
        ),
    ]
